version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 112358
    volumes:
      - "./data/db:/data/db"
      - "./data/configdb:/data/configdb"
      - "./data/dump:/home/dump"
      - "./data/import:/home/import"
    ports:
      - 27017:27017
    networks:
      - db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 112358
    depends_on:
      - mongo
    networks:
      - db

volumes:
  datadb:
  configdb:

networks:
  db: